// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipientId");

                    b.HasIndex("Status");

                    b.ToTable("Notifications", (string)null);

                    b.HasDiscriminator<string>("Channel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.EmailNotification", b =>
                {
                    b.HasBaseType("NotificationHub.Domain.Entities.Notification");

                    b.PrimitiveCollection<List<string>>("AttachmentUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("AttachmentUrls");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.PushNotification", b =>
                {
                    b.HasBaseType("NotificationHub.Domain.Entities.Notification");

                    b.HasDiscriminator().HasValue("Push");
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.SmsNotification", b =>
                {
                    b.HasBaseType("NotificationHub.Domain.Entities.Notification");

                    b.HasDiscriminator().HasValue("Sms");
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.WhatsAppNotification", b =>
                {
                    b.HasBaseType("NotificationHub.Domain.Entities.Notification");

                    b.PrimitiveCollection<List<string>>("BodyParameters")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("WhatsAppBodyParams");

                    b.PrimitiveCollection<List<string>>("FooterParameters")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("WhatsAppFooterParams");

                    b.PrimitiveCollection<List<string>>("HeaderParameters")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("WhatsAppHeaderParams");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasDiscriminator().HasValue("WhatsApp");
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.EmailNotification", b =>
                {
                    b.OwnsMany("NotificationHub.Domain.ValueObjects.EmailAddress", "Bcc", b1 =>
                        {
                            b1.Property<Guid>("EmailNotificationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254);

                            b1.HasKey("EmailNotificationId", "__synthesizedOrdinal");

                            b1.ToTable("Notifications");

                            b1
                                .ToJson("EmailBcc")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EmailNotificationId");
                        });

                    b.OwnsMany("NotificationHub.Domain.ValueObjects.EmailAddress", "Cc", b1 =>
                        {
                            b1.Property<Guid>("EmailNotificationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254);

                            b1.HasKey("EmailNotificationId", "__synthesizedOrdinal");

                            b1.ToTable("Notifications");

                            b1
                                .ToJson("EmailCc")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EmailNotificationId");
                        });

                    b.OwnsOne("NotificationHub.Domain.ValueObjects.EmailAddress", "From", b1 =>
                        {
                            b1.Property<Guid>("EmailNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("EmailFrom");

                            b1.HasKey("EmailNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("EmailNotificationId");
                        });

                    b.OwnsOne("NotificationHub.Domain.ValueObjects.EmailAddress", "ReplyTo", b1 =>
                        {
                            b1.Property<Guid>("EmailNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("EmailReplyTo");

                            b1.HasKey("EmailNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("EmailNotificationId");
                        });

                    b.OwnsOne("NotificationHub.Domain.ValueObjects.EmailAddress", "To", b1 =>
                        {
                            b1.Property<Guid>("EmailNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("EmailTo");

                            b1.HasKey("EmailNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("EmailNotificationId");
                        });

                    b.Navigation("Bcc");

                    b.Navigation("Cc");

                    b.Navigation("From");

                    b.Navigation("ReplyTo");

                    b.Navigation("To")
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.SmsNotification", b =>
                {
                    b.OwnsOne("NotificationHub.Domain.ValueObjects.PhoneNumber", "FromNumber", b1 =>
                        {
                            b1.Property<Guid>("SmsNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("SmsFromNumber");

                            b1.HasKey("SmsNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("SmsNotificationId");
                        });

                    b.OwnsOne("NotificationHub.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("SmsNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("SmsPhoneNumber");

                            b1.HasKey("SmsNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("SmsNotificationId");
                        });

                    b.Navigation("FromNumber");

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Domain.Entities.WhatsAppNotification", b =>
                {
                    b.OwnsOne("NotificationHub.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("WhatsAppNotificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("WhatsAppPhoneNumber");

                            b1.HasKey("WhatsAppNotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("WhatsAppNotificationId");
                        });

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
